{{- if .Values.dockerSecret }}
{{- if .Values.dockerSecret.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "toucantoco-frontend.pullsecretname" . }}
  labels:
    {{- include "toucantoco-frontend.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerSecret.config | b64enc }}
{{- end }}
{{- end }}
