replicaCount: 1

image:
  repository: ghcr.io/w6d-io/chopper/front
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  name: ""   # leave blank to use fullname
  
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: []
