replicaCount: 1

image:
  repository: ghcr.io/w6d-io/chopper
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true
  name: ""   # leave blank to use fullname

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: chopper.example.com
      path: /
      pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: []

env:
  VITE_API_BASE_URL: "http://localhost:8080"
  PORT: "8080"
  NODE_ENV: "development"
  VITE_NODE_ENV: "development"
  API_CONFIGS: "infractions:http://localhost:8000:local"
  DEFAULT_TENANT: "business"
  DEFAULT_LANGUAGE: "en"
