{{- if .Values.postgresqlSimple.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ .Release.Name }}-postgresql-hl
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresqlSimple.image.repository }}:{{ .Values.postgresqlSimple.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresqlSimple.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresqlSimple.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresqlSimple.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgresqlSimple.auth.username }}"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgresqlSimple.auth.username }}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.postgresqlSimple.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresqlSimple.persistence.size }}
{{- end }}
