apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-connect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: kafka-connect
        {{- include "kafka-connect.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka-connect.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- toYaml .Values.initContainers | nindent 6 }}
      {{- if .Values.volumeMounts }}
        volumeMounts:
        {{- toYaml .Values.volumeMounts | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        env:
          - name: BOOTSTRAP_SERVERS
            value: {{ .Values.config.bootstrap_servers }}
          - name: GROUP_ID
            value: {{ .Values.config.group_id }}
          - name: OFFSET_STORAGE_TOPIC
            value: {{ .Values.config.topics.offsets }}
          - name: CONFIG_STORAGE_TOPIC
            value: {{ .Values.config.topics.config }}
          - name: STATUS_STORAGE_TOPIC
            value: {{ .Values.config.topics.status }}
          {{- if .Values.connector }}
          - name: CONNECT_PLUGIN_PATH
            value: {{ include "plugin.path" . }}
          {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: {{ .Chart.Name }}
            containerPort: 8083
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- if .Values.connector }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - /scripts/connector.sh
      {{- end }}
        volumeMounts:
        - mountPath: /data
          name: connector
        - mountPath: /scripts
          name: scripts
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end}}
      - name: connector
        secret:
          defaultMode: 0444
          secretName: {{ include "kafka-connect.fullname" . }}
      - name: scripts
        configMap:
          defaultMode: 0555
          name: {{ include "kafka-connect.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
