{{- if .Values.schema_registry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-connect.fullname" . }}-schema-registry
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8083
      protocol: TCP
      name: {{ .Chart.Name }}
  selector:
    {{- include "kafka-connect.selectorLabels" . | nindent 4 }}
    component: schema-registry
{{- end }}
