{{- if .Values.secrets_init }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "kafka-connect.fullname" . }}-init"
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secrets_init }}
    {{ .key }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
