apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  connector.json: |-
    {
      "name": "containers-connector",
      "config": {
          "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
          "plugin.name": "pgoutput",
          "database.hostname": {{ .Values.connector.database.hostname | quote }},
          "database.port": {{ default "5432" .Values.connector.database.port | quote }},
          "database.user": {{ default "postgres" .Values.connector.database.user | quote }},
          "database.password": {{ .Values.connector.database.password | quote }},
          "database.dbname": {{ .Values.connector.database.name | quote }},
          "database.server.name": {{ .Values.connector.database.name | quote }},
          "database.include.list": {{ .Values.connector.database.list | quote }}
      }
    }
