{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "helper.labels.standard" . | nindent 4 }}
  name: {{ include "ciops.serviceAccountName" . }}
{{ if or .Values.serviceAccount.token .Values.vault.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ include "ciops.serviceAccountName" . }}
  name: {{ printf "%s-token" (include "ciops.serviceAccountName" .) }}

{{- end }}
{{- end }}
