---
replicaCount: 1

image:
  repository: 'nginx'
  tag: 'alpine'

lifecycle:
  enabled: false

annotations: {}

initContainers: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

service:
  name: 'app'
  internalPort: 8080
  externalPort: 8080
  type: ClusterIP

externalsvc: {}

ingress:
  enabled: true
  host: ''
  path: /
  issuer: ''
  class: 'nginx'
  prefix: 'nginx.ingress.kubernetes.io'
  extraPaths: []

persistence: []
livenessProbe: {}
readinessProbe: {}

metrics:
  enabled: false
  path: '/metrics'
  port: 8080

configs: []
secrets: []

nodeSelector: {}

volumeMounts: {}
volumes: {}
