---
replicaCount: 1

name: "-"

id: ""
namespace: ""

kind: ""

database:
  host: ""
  adminpassword: ""
  password: ""
  postgres_password: ""
  component: ""
  enabled: false

generateSecret:
  enabled: false

liquibase:
  enabled: false

strategy: {}
#  type: Recreate
# Rollout sample
# canary:
#   maxSurge: 3
#   maxUnavailable: 0
#   canaryService: app-canary
#   stableService: app
#   steps:
#     - setWeight: 50
#     - pause: {}

revision:
  enabled: false

image:
  repository: 'nginx'
  tag: 'alpine'

serviceAccount:
  create: true
  token: true
  annotations: {}

role:
  rules: null

podSecurityPolicy:
  enabled: false

podAnnotations: {}
podLabels: {}

defaultContainer: ""

lifecycle:
  enabled: false

resources: {}

service:
  name: "-"
  internalPort: 8080
  externalPort: 8080
  type: ClusterIP

externalsvc: {}

ingress:
  enabled: false
  externaldns: null
  host: ''
  path: /
  issuer: ''
  class: 'nginx'
  prefix: 'nginx.ingress.kubernetes.io'
  className: ''         # ingressClassName field https://kubernetes.github.io/ingress-nginx/#what-is-ingressclassname-field
  extraPaths: []
  annotations: {}
  secretName: ''

cert:
  enabled: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: ""
  dnsNames: []

metrics:
  enabled: false
  path: '/metrics'
  port: 8080

env: ""
extraEnv: ""

configs: []

secrets: []

nodeSelector: {}

volumeMounts: {}
volumes: {}
extraVolumes: []
extraVolumeMounts: []
autoscaling:
  enabled: false

extraResources: ""

mongodb:
  install: false

redis:
  install: false

pdb:
  enabled: false

vault:
  enabled: true
  url: http://vault.vault:8200
  envFrom:
    enabled: false
    path: strada/data

linkerd:
  enabled: false

httproute:
  enabled: false
  host: ''
  gateway: ''
  path: '/'
  rewrite: false
  rewritepath: '/'

backendpolicy:
  securityPolicy: 'gke-regional'
  logging: true
  sampleRate: 1000000

initContainers: []

healthcheck:
  enabled: false
  config:
    port: 80
    type: HTTP  # Can be HTTP, HTTPS, or TCP
    path: /
    host: ""
    timeout: "5s"
    checkInterval: "10s"
    healthyThreshold: 2
    unhealthyThreshold: 3
