---
replicaCount: 1

name: "-"

id: ""
namespace: ""
database:
  host: ""
  adminpassword: ""
  password: ""
  postgres_password: ""
  component: ""
generateSecret:
  enabled: false

liquibase:
  enabled: false

revision:
  enabled: false

image:
  repository: 'nginx'
  tag: 'alpine'

serviceAccount:
  create: false
  token: true
  annotations: {}
  name: "app"

role:
  rules: null

podSecurityPolicy:
  enabled: false

lifecycle:
  enabled: false

resources: {}

service:
  name: "-"
  internalPort: 8080
  externalPort: 8080
  type: ClusterIP

externalsvc: {}

ingress:
  enabled: false
  host: ''
  path: /
  issuer: ''
  class: 'nginx'
  prefix: 'nginx.ingress.kubernetes.io'
  className: ''         # ingressClassName field https://kubernetes.github.io/ingress-nginx/#what-is-ingressclassname-field
  extraPaths: []

cert:
  enabled: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: ""
  dnsNames: []

metrics:
  enabled: false
  path: '/metrics'
  port: 8080

env: "-"

configs: []

secrets: []

nodeSelector: {}

volumeMounts: {}
volumes: {}

autoscaling:
  enabled: false

extraResources: ""

mongodb:
  install: false

redis:
  install: false

pdb:
  enabled: false
