{{- if .Values.liquibase.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "global.names.name" . }}-sql
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  {{- (.Files.Glob "sql/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "global.names.name" . }}-dbscript
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  initdb: |-
    {{- include (print $.Template.BasePath "/liquibase/_initdb.tpl") . | nindent 4 }}
{{- end }}