{{- if .Values.liquibase.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  name: {{ printf "%s-init" .Release.Name }}
type: Opaque
data:
  postgres-password: {{ required "database.postgres_password is required" .Values.database.postgres_password | b64enc }}
{{- end }}