{{- if .Values.liquibase.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  name: {{ include "app.serviceAccountName" . }}-db
{{- end }}

