{{- if and .Values.siteOperator.enabled .Values.siteOperator.installCRDs }}
---
{{ include "auth.sites.crd" (dict "ctx" . "file" "auth.w6d.io_sites.yaml") }}
---
{{ include "auth.sites.crd" (dict "ctx" . "file" "auth.w6d.io_zones.yaml") }}
{{- if .Values.siteOperator.gateway.enabled }}
---
{{ include "auth.sites.crd" (dict "ctx" . "file" "auth.w6d.io_gateways.yaml") }}
{{- end }}
{{- end }}
