apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "helper.labels.standard" $ | nindent 4 }}
  name: {{ include "dlm.names.fullname" . }}
data:
  config.yaml: |
    {{- toYaml .Values.controller.config | nindent 4 }}
