---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-leader-election-role
  namespace: {{ include "ci-operator.namespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-leader-election-rolebinding
  namespace: {{ include "ci-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ include "ci-operator.namespace" . }}
