{{- if .Values.webhook.enabled }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ci-serving-cert
spec:
  dnsNames:
    - ci-webhook-service.{{ .Release.Namespace }}.svc
    - ci-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ci-selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}