{{- if or .Values.webhook.enabled .Values.metrics.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ci-serving-cert
  labels:
    {{- include "ci-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - ci-webhook-service.{{ .Release.Namespace }}.svc
    - ci-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ci-selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}
