apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "helper.labels.standard" $ | nindent 4 }}
  name: {{ printf "%s-webhook" (include "dlm.names.fullname" .) }}
data:
  config.yaml: |
    {{- toYaml .Values.webhook.config | nindent 4 }}
