{{- if .Values.webhook.autoscaling.enabled }}
{{- $fullname := (include "dlm.names.fullname" .) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-webhook" $fullname }}
  labels:
    {{- include "helper.labels.standard" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-webhook" $fullname }}
  minReplicas: {{ .Values.webhook.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webhook.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.webhook.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.webhook.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ include . }}
  {{- end }}
{{- end }}
