{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth-external-auth.fullname" . }}
  labels:
    {{- include "oauth-external-auth.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.clientSecret | b64enc }}
  cookie-secret: {{ .Values.cookieSecret | b64enc }}
{{- end }}
