configs:
  - key: config.yaml
    kind: volume
    subPath: triggers.yaml
    name: CONFIG
    path: /data/etc
    value: |-
      config:
        content: "config test"
secrets:
  - key: secret-volume.yaml
    kind: volume
    name: SECRET_VOLUME
    subPath: secret-volume.yaml
    path: /data/config
    value: |-
      secret:
        token: "token-secret"
        password: "password-test"
env:
  - name: ENV_ONE
    value: "1"
  - name: ENV_TWO
    value: text
fullnameOverride: test-chart
nameOverride: test
metrics:
  enabled: true
  port: 8082
mongodb:
  auth:
    database: test
    password: password-for-testing
    rootPassword: root-password-for-testing
    username: test
  fullnameOveride: test-mongodb
  install: true
podLabels:
  application: test
redis:
  auth:
    password: password-fot-testing
  fullnameOveride: test-redis
  install: true

service:
  internalPort: 8080
  name: test
serviceAccount:
  create: true
  name: test
