{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auth.fullname" . }}-backup
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- with .Values.backup.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
