apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nager.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "nager.name" . }}
