apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotenberg.fullname" . }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "gotenberg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gotenberg.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gotenberg.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "gotenberg.name" . }}
          image: {{ include "gotenberg.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- range $k, $v := . }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp/gotenberg
            - name: home
              mountPath: /home/gotenberg
      volumes:
        - name: tmp
          emptyDir:
            {{- with .Values.volumes.tmp.medium }}
            medium: {{ . }}
            {{- end }}
            {{- with .Values.volumes.tmp.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
        - name: home
          emptyDir:
            {{- with .Values.volumes.home.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
