---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "toucantoco-backend.fullname" . }}
  labels:
    {{- include "toucantoco-backend.labels" . | nindent 4 }}
type: Opaque
data:
  user-superadmin-password: {{ .Values.userSuperadminPassword | b64enc | quote }}
  jwt-secret-key: {{ .Values.jwtSecretKey | b64enc | quote }}
  db-encryption-secret: {{ .Values.dbEncryptionSecret | b64enc | quote }}
  {{- if .Values.smtp.enabled }}
  stmp-password: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
  mongodb-password: {{ .Values.mongodb.password | b64enc | quote }}
  mongodb-readonly-password: {{ .Values.mongodb.readonlyUser.password | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
