{{- if .Values.cert.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "tools.labels.standard" . | nindent 4 }}
  name: {{ include "tools.names.fullname" . }}
spec:
  dnsNames:
    {{- range .Values.cert.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef: {{ toYaml .Values.cert.issuerRef | nindent 4}}
  secretName: {{ default (printf "%s-tls" (include "tools.names.fullname" .) ) .Values.cert.secretName }}
  usages:
    - digital signature
    - key encipherment
{{- end }}