{{- if .Values.configs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "common.names.fullname" . }}
data:
{{- range .Values.configs }}
  {{ .key }}: {{ toYaml .value | indent 2 }}
{{- end }}
{{- end }}
