{{- if .Values.configs }}
{{- range .Values.configs }}
{{- $name := .name | lower | replace "_" "-" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "tools.labels.standard" $ | nindent 4 }}
  name: {{ printf "%s-%s" (include "tools.names.fullname" $) $name }}
data:
  {{ .key }}: {{ toYaml .value | indent 2 }}
{{- end }}
{{- end }}
