{{- $labels := (include "common.labels.standard" .) }}
{{- $fullname := (include "common.names.fullname" .) }}
{{- range .Values.configs }}
{{- $name := .name | lower | replace "_" "-" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- (include "common.labels.standard" $) | nindent 4 }}
  name: {{ printf "%s-%s" $fullname $name }}
data:
  {{- if not (empty .subPath) }}
  {{ .key }}: |
    {{- .value | nindent 4}}
  {{- else }}
  {{- .value | nindent 2}}
  {{- end }}
{{- end }}
