{{- if and .Values.httproute.enabled (not .Values.ingress.enabled) -}}
{{- $name := .Values.service.name -}}
{{- $svcPort := .Values.service.externalPort -}}
{{- $host := .Values.httproute.host }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $name }}
spec:
  parentRefs:
  - name: {{ .Values.httproute.gateway }}
    namespace: gateway
  hostnames: 
  - {{ $host }}
  rules:
  - matches:
    - type: PathPrefix
      value: {{ .Values.httproute.path }}
    backendRefs:
    - group: ''
      kind: Service
      name: {{ $name }}
      port: {{ $svcPort }}
      weight: 1
{{- end }}
