{{- if and .Values.httproute.enabled (not .Values.ingress.enabled) -}}
{{- $name := .Values.service.name -}}
{{- $svcPort := .Values.service.externalPort -}}
{{- $host := .Values.httproute.host }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  labels:
    {{- include "helper.labels.standard" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.httproute.gateway }}
    namespace: gateway
  hostnames: 
  - {{ $host }}
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: {{ $name }}
      port: {{ $svcPort }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.httproute.path }}
    {{- if .Values.httproute.rewrite }}
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: {{ .Values.httproute.rewritepath }}
    {{- end }}
{{- end }}
