{{- if .Values.httproute.enabled -}}
{{- $name := .Values.service.name -}}
{{- $svcPort := .Values.service.externalPort -}}
{{- $host := include "httproute.host" . }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $name }}
spec:
  parentRefs:
  - name: {{ .Values.httproute.gateway }}
    namespace: gateway
  hostnames: 
  - {{ $host }}
  rules:
  - matches:
    - path:
      type: PathPrefix
      value: {{ .Values.httproute.path }}
    backendRefs:
    - name: {{ $name }}
      port: {{ $svcPort }}
{{- end }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ $name }}
spec:
  default:
    securityPolicy: {{ .Values.httproute.securityPolicy }}
    logging:
      enabled: {{ .Values.httproute.logging }}
      sampleRate: {{ .Values.httproute.sampleRate }}
  targetRef:
    group: ""
    kind: Service
    name: {{ $name }}
---