{{- if and .Values.ingress.enabled .Values.ingress.host }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" .}}
kind: Ingress
metadata:
  annotations:
    {{- (include "common.ingress.annotations" (dict "ingress" .Values.ingress "context" $)) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ include "common.names.fullname" . }}
spec:
  {{- include "common.ingress.className" (dict "ingress" .Values.ingress "context" $) | nindent 2}}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        {{- if eq (include "common.ingress.supportsPathType" .) "true" }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- (include "common.ingress.backend" (dict "serviceName" .Values.service.name "serviceTarget" .Values.service.externalPort "context" $)) | nindent 10 }}
      {{- if .Values.ingress.extraPaths }}
      {{- (include "common.ingress.paths" (dict "paths" .Values.ingress.extraPaths "context" $)) | nindent 6 }}
      {{- end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    {{- if .Values.ingress.secretName }}
    secretName: {{ include "common.names.name" . }}-tls
    {{- end }}
{{- end }}
