{{- if .Values.networkPolicies }}
  {{- $labels := (include "common.labels.standard" .) }}
  {{- $fullname := (include "global.names.fullname" .) }}
  {{- $name := (include "global.names.name" .) }}
  {{- range .Values.networkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- if $.Values.annotations }}
  annotations:
  {{ toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
  name: {{ $fullname }}-{{ .name }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels.matchLabels" $ | nindent 6}}
  policyTypes:
    {{- toYaml .types | nindent 4 }}
  {{- if .ingress }}
  ingress:
    {{- toYaml .ingress | nindent 4 }}
  {{- end }}
  {{- if .egress }}
  egress:
    {{- toYaml .egress | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
