{{- if .Values.podSecurityPolicy.enabled }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ include "common.names.fullname" . }}
spec:
  privileged: false  # Don't allow privileged pods!
  allowPrivilegeEscalation: false # prevent from setuid
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
{{- end }}
