{{- if .Values.persistence -}}
  {{- $labels := (include "helper.labels.standard" .) }}
  {{- $fullname := (include "app.names.fullname" .) }}
{{ range .Values.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- $labels | nindent 4 }}
  name: {{ $fullname }}-{{ .name }}
spec:
  accessModes:
  - {{ default "ReadWriteOnce" .mode }}
  resources:
    requests:
      storage: {{ default "1Gi" .size }}
  {{- include "helper.storage.class" ( dict "persistence" . ) | nindent 2 }}
  volumeMode: {{ default "Filesystem" .volumeMode }}
{{- end -}}
{{- end -}}
