{{- if or .Values.lifecycle.enabled .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: role-{{ template "app.fullname" . }}-svc
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: role-{{ template "app.fullname" . }}-pod
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - patch
{{- if .Values.role.rules }}
{{- range .Values.role.rules -}}
- apiGroups:
  {{- toYaml .apiGroups | nindent 2 }}
  {{- if .resources }}
  resources:
  {{- toYaml .resources | nindent 2 }}
  {{- end }}
  {{- if .resourceNames }}
  resourceNames:
  {{- toYaml .resourceNames | nindent 2 }}
  {{- end }}
  {{- if .nonResourceURLs }}
  nonResourceURLs:
  {{- toYaml .nonResourceURLs | nindent 2 }}
  {{- end }}
  {{- if .verbs }}
  verbs:
  {{- toYaml .verbs | nindent 2 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
