{{- if or .Values.lifecycle.enabled .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: role-{{ template "app.fullname" . }}-svc
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: role-{{ template "app.fullname" . }}-pod
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - patch
{{- end }}
