{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "common.names.fullname" . }}
type: Opaque
data:
{{- range .Values.secrets }}
  {{ .key }}: {{ tpl .value $ | b64enc }}
{{- end }}
{{- end }}
<<<<<<< HEAD
{{- if and (not .Values.global.generateSecret.enabled) .Values.liquibase.enabled }}
=======
{{- if and (not .Values.global.generateSecret.enabled) .Values.liquibase.enabled}
>>>>>>> c39bb79 (fix secret check)
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "common.names.fullname" . }}-db
type: Opaque
data:
  postgres-password: {{ required "global.database.password is required" (include "global.database.password" .) | b64enc }}
  dlm-postgres-password: {{ required "global.database.adminpassword is required" (include "global.database.adminpassword" .) | b64enc }}
---
{{- end }}
