{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "global.names.fullname" . }}
type: Opaque
data:
{{- range .Values.secrets }}
  {{ .key }}: {{ tpl .value $ | b64enc }}
{{- end }}
{{- end }}
{{- if and (not .Values.generateSecret.enabled) (or .Values.liquibase.enabled .Values.database.enabled ) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "global.names.fullname" . }}-db
type: Opaque
data:
  postgres-password: {{ required "database.password is required" .Values.database.password | b64enc }}
  dlm-postgres-password: {{ required "database.adminpassword is required" .Values.database.adminpassword | b64enc }}
---
{{- end }}
