{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ include "common.names.fullname" . }}
type: Opaque
data:
{{- range .Values.secrets }}
  {{ .key }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
{{- if and .Values.dockerSecret .Values.dockerSecret.config }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: pull-{{ include "common.names.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerSecret.config | b64enc }}
{{- end }}
