{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ include "global.serviceAccountName" . }}
{{ if and .Values.serviceAccount.token (semverCompare ">=1.24.x" (include "common.capabilities.kubeVersion" .)) }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ include "global.serviceAccountName" . }}
  name: {{ printf "%s-token" (include "global.serviceAccountName" .) }}

{{- end }}
{{- end }}
