{{- if and .Values.externalsvc .Values.externalsvc.namespaceTarget }}
  {{- $serviceName := (include "helper.names.service" (dict "name" .Values.service.name "context" $)) }}
  {{- $externalName := printf "%s.%s.%s" $serviceName .Release.Namespace "svc.cluster.local" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helper.labels.standard" . | nindent 4 }}
  name: {{ .Values.externalsvc.name | default $serviceName }}
  namespace: {{ .Values.externalsvc.namespaceTarget }}
spec:
  type: ExternalName
  externalName: {{ $externalName }}
{{- end }}

