{{- $serviceName := (include "helper.names.service" (dict "name" .Values.service.name "context" $)) }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helper.labels.standard" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $serviceName }}
spec:
  ports:
  - name: {{ $serviceName | trunc 14 | trimSuffix "-" }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: {{ default (include "app.names.name" . | trunc 14 | trimSuffix "-") (default .Values.service.internalPort .Values.service.targetPort) }}
  {{- if .Values.metrics.enabled }}
    {{- if ne (.Values.metrics.port | int) (.Values.service.internalPort | int ) }}
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
    {{- end }}
  {{- end }}
  {{- if .Values.extraContainerPort }}
    {{- range .Values.extraContainerPort }}
  - name: {{ .name | trunc 14 | trimSuffix "-" }}
    port: {{ .port }}
    {{- if .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
    protocol: {{ default "TCP" .protocol }}
    targetPort: {{ default (.name | trunc 14 | trimSuffix "-") .target }}
    {{- end }}
  {{- end }}
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    {{- include "helper.labels.matchLabels" . | nindent 4 }}
