{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: ci-controller-manager-metrics-monitor
  namespace: {{ include "ci-operator.namespace" . }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      {{- include "ci-operator.selectorLabels" . | nindent 6 }}
{{- end }}