{{- if or .Values.namespaceAnnotations .Values.namespaceLabels }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  name: rolebinding-{{ include "common.names.name" . }}-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-{{ include "common.names.name" . }}-ns
subjects:
  - kind: ServiceAccount
    name: {{ include "common.serviceAccountName" . }}-ns
    namespace: {{ .Release.Namespace }}
{{- end }}
