{{- if or .Values.namespaceAnnotations .Values.namespaceLabels -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    {{- include "tools.labels.standard" . | nindent 4 }}
  name: {{ include "app.serviceAccountName" . }}-ns
{{- end }}

