apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ci-operator.fullname" . }}
  namespace: {{ include "ci-operator.namespace" . }}
  labels:
    {{- include "ci-operator.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config | b64enc | quote }}
