apiVersion: v1
kind: Service
metadata:
  name: {{ include "ci-operator.fullname" . }}
  labels:
    {{- include "ci-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8443
    targetPort: https
    name: https
  selector:
    {{- include "ci-operator.selectorLabels" . | nindent 4 }}
