-- Roles
CREATE ROLE {{db_username}} WITH
LOGIN
INHERIT
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOREPLICATION
PASSWORD '{{db_password}}';

CREATE ROLE {{db_admin_username}} WITH
LOGIN
INHERIT
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOREPLICATION
PASSWORD '{{db_admin_password}}';
