apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-operator.fullname" .  | default "kafka-operator" }}
  labels:
    control-plane: kafka-controller
  {{- include "kafka-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: kafka-controller
    {{- include "kafka-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: kafka-controller
      {{- include "kafka-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
        - name: manager
          image: {{ include "kafka-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect={{ .Values.operator.leaderElection }}
            - --metrics-bind-address={{ include "kafka-operator.metricsAddress" . }}
            - --health-probe-bind-address={{ include "kafka-operator.probeAddress" . }}
            - --zap-log-level={{ .Values.operator.logLevel }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}