apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-operator-role
  labels:
  {{- include "kafka-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kafka.kafka.w6d.io
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.kafka.w6d.io
  resources:
  - kafkatopics/finalizers
  verbs:
  - update
- apiGroups:
  - kafka.kafka.w6d.io
  resources:
  - kafkatopics/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-operator-rolebinding
  labels:
  {{- include "kafka-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka-operator.fullname" . }}-kafka-operator-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka-operator.fullname" .  | default "kafka-operator" }}'
  namespace: '{{ .Release.Namespace }}'
