apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-operator.fullname" .  | default "kafka-operator" }}
  labels:
  {{- include "kafka-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
