{{- if and (not .Values.generateSecret.enabled ) .Values.liquibase.enabled  }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-create-secrets
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  #  ttlSecondsAfterFinished: 5
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}-secret
      restartPolicy: Never
      containers:
        - name: gen-secret
          image: "w6dio/kubectl:v1.4.0"
          command: ['/bin/bash', '/scripts/create-secrets']
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "common.names.name" . }}-script
  {{- end -}}