{{- if and (not .Values.global.generateSecret.enabled ) .Values.liquibase.enabled  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  name: rolebinding-{{ include "common.names.name" . }}-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-{{ include "common.names.name" . }}-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "common.serviceAccountName" . }}-secret
    namespace: {{ .Release.Namespace }}
{{- end }}