apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ printf "%s-secret" (include "common.serviceAccountName" .) | quote}}